package HW_3;

public class Main {
    public static void main(String[] args) throws MyException {
        Collection coll = new Collection();







        /*
        try {
            Figure f1 = new Triangle(new Integer[]{8, 10, 4});
            System.out.println(f1.getName());
            System.out.println(((Triangle)f1).perimeter());
            System.out.println(((Triangle)f1).area());
            }
            catch (MyException e){
                System.out.println(e.getMessage());
            }

        try {
            Figure f2 = new Rectangle(new Integer[]{20, 11});
            System.out.println(f2.getName());
            System.out.println(((Rectangle)f2).perimeter());
            System.out.println(((Rectangle)f2).area());
        }
        catch (MyException e){
            System.out.println(e.getMessage());
        }
        try {
            Figure f3 = new Square(3);
            System.out.println(f3.getName());
            System.out.println(((Square)f3).perimeter());
            System.out.println(((Square)f3).area());
        }
        catch (MyException e){
            System.out.println(e.getMessage());
        }

        try {
            Figure f6 = new Rectangle(new Integer[]{20, 110});
            System.out.println(f6.getName());
            System.out.println(((Rectangle)f6).perimeter());
            System.out.println(((Rectangle)f6).area());
        }
        catch (MyException e){
            System.out.println(e.getMessage());
        }

        try {
            Figure f4 = new Circle(0);
            System.out.println(f4.getName());
            System.out.println(((Circle)f4).circumference());
            System.out.println(((Circle)f4).area());
        }
        catch (MyException e){
            System.out.println(e.getMessage());
        }

        try {
            Figure f5 = new Circle(1);
            System.out.println(f5.getName());
            System.out.println(((Circle)f5).circumference());
            System.out.println(((Circle)f5).area());
        }
        catch (MyException e){
            System.out.println(e.getMessage());
        }
        */

    
}

}
